# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mattiav90.github.io/TestProject/"

git_url = "https://github.com/mattiav90/TestProject/tree/master/"

def custom_doc_links(name): return None
